### ISSUE TITLE
search box pada navbar

### ISSUE THREAD

**Issue by n0tlu5** [2018-PemrogramanWeb-D/tugas7-fp-simbeasiswa#2]
fitur search pada navbar mengembalikan error 404 : action_page.php not found

![image](https://user-images.githubusercontent.com/20925605/50147448-bf7fc200-02e8-11e9-8a0e-9f194af9076b.png)

**Comment by affanhabib** [comment]
sudah bisa fitur search

![image](https://user-images.githubusercontent.com/37770387/50331250-a5382500-0530-11e9-9ee2-8653b3b46568.png)
