### ISSUE TITLE
Halaman tidak ditemukan issue

### ISSUE THREAD

**Issue by Armunz** [2018-PemrogramanWeb-D/tugas7-fp-simbeasiswa#5]
halaman contact tidak ditemukan
![halaman sistem informasi tidak ada](https://user-images.githubusercontent.com/36951196/50162686-83ad2280-0311-11e9-8a92-717cde507ef1.jpg)
halaman sistem informasi tidak ditemukan
![ketika klik cari halaman tidak ada](https://user-images.githubusercontent.com/36951196/50162687-8445b900-0311-11e9-87c7-e9d2d25125f3.jpg)
halaman cari tidak ditemukan
![halaman contact tidak ada](https://user-images.githubusercontent.com/36951196/50162688-8445b900-0311-11e9-954d-6756397ae45c.jpg)

**Comment by 051mym** [comment]
Halaman kategori tidak ditemukan

![simbeasiswa2](https://user-images.githubusercontent.com/42793951/50163063-3c736180-0312-11e9-850b-3355946c9718.JPG)

**Comment by affanhabib** [comment]
sudah bisa

![image](https://user-images.githubusercontent.com/37770387/50331202-7326c300-0530-11e9-91d9-35347e8b2613.png)
![image](https://user-images.githubusercontent.com/37770387/50331210-8043b200-0530-11e9-9405-b5bddd23d846.png)
![image](https://user-images.githubusercontent.com/37770387/50331217-86399300-0530-11e9-8d8c-53e6ba61ded7.png)
