### ISSUE TITLE
Fitur upload ada tanpa akses admin

### ISSUE THREAD

**Issue by Neorocket64** [2018-PemrogramanWeb-D/tugas7-fp-simbeasiswa#7]
![capture](https://user-images.githubusercontent.com/17949796/50189443-c7c31600-0357-11e9-829c-ee7e52f7a2bb.PNG)

**Comment by affanhabib** [comment]
upload memang semua orang bisa mengakses. berfungsi untuk jika ada info beasiswa dan ingin menyebarluaskan
