### ISSUE TITLE
link navbar pada halaman blog tidak redirect seperti lainnya

### ISSUE THREAD

**Issue by Neorocket64** [2018-PemrogramanWeb-D/tugas7-fp-simbeasiswa#8]
Tidak melakukan apapun jika diklik (tidak seperti lainnya)
![capture](https://user-images.githubusercontent.com/17949796/50189566-5768c480-0358-11e9-9a89-aed144ce3109.PNG)

**Comment by affanhabib** [comment]
Fitur blog sekarang sudah dihapus
